### PR TITLE
use single quotes everywhere

### PR DESCRIPTION
**Pull request by SDEagle**
The use of single vs. double quotes differs right now all over the place. This PR would change that to consistent use of single quotes everywhere.

### CODE REVIEW

**Comment by princemaple** [comment]
There have been several fights about which quotation mark to use. I'll merge this since you unified all the cases, and this is my personal preference too.

**Comment by SDEagle** [comment]
well, a config option would probably be best... But I though unifying is a good start :)

**Comment by princemaple** [comment]
True. And True. :+1:

**Comment by rahilsondhi** [comment]
How can I change everything to double quotes locally?

**Comment by princemaple** [comment]
The way I recommend is: install the package via package control, extract the package with https://packagecontrol.io/packages/Extract%20Sublime%20Package, modify the snippets as you wish, delete the rest (e.g. python files), then move your change to `User`, so you can keep your change and continue to receive updates.

**Pull request merged**
